/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef OPENOCD_RTOS_PADOS_H
#define OPENOCD_RTOS_PADOS_H

/*
 * Wire layout of PadOS debugger interface version 2.
 * The authoritative definition is Include/Kernel/KDebugger.h in PadOS.
 * Descriptor entries are target-endian 32-bit words, including pointers.
 * Offsets and state values come from the firmware, not its C++ ABI.
 */
enum pados_info_field {
	PADOS_VERSION,
	PADOS_SIZE,
	PADOS_ARCHITECTURE,
	PADOS_POINTER_SIZE,
	PADOS_THREADS,
	PADOS_THREAD_LIST_FIRST_OFFSET,
	PADOS_THREAD_NODE_OFFSET,
	PADOS_CURRENT_THREAD,
	PADOS_THREAD_NEXT_OFFSET,
	PADOS_THREAD_ID_OFFSET,
	PADOS_THREAD_NAME_OFFSET,
	PADOS_THREAD_NAME_SIZE,
	PADOS_THREAD_STATE_OFFSET,
	PADOS_THREAD_STATE_SIZE,
	PADOS_THREAD_PRIORITY_OFFSET,
	PADOS_THREAD_STACK_OFFSET,
	PADOS_THREAD_SYSCALL_RETURN_OFFSET,
	PADOS_PRIORITY_MINIMUM,
	PADOS_THREAD_STATE_COUNT,
	PADOS_THREAD_STATES,
	PADOS_STACK_POINTER_MASK,
	PADOS_EXCEPTION_RETURN_OFFSET,
	PADOS_BASIC_FRAME_SIZE,
	PADOS_EXTENDED_FRAME_SIZE,
	PADOS_CORE_REGISTER_COUNT,
	PADOS_BASIC_REGISTER_OFFSETS,
	PADOS_EXTENDED_REGISTER_OFFSETS,
	PADOS_FLOATING_POINT_REGISTER_COUNT,
	PADOS_FLOATING_POINT_REGISTER_OFFSETS,
	PADOS_THREAD_KERNEL_TLS_OFFSET,
	PADOS_THREAD_USERSPACE_TLS_OFFSET,
	PADOS_TLS_DATA_OFFSET,
	PADOS_INFO_COUNT,
};

#define PADOS_INTERFACE_VERSION 2
#define PADOS_ARCH_CORTEX_M 1
/* qGetTLSAddr load-module IDs defined by the PadOS debugger interface. */
#define PADOS_TLS_MODULE_KERNEL 1
#define PADOS_TLS_MODULE_USERSPACE 2
#define PADOS_REGISTER_SP UINT16_MAX
/* PadOS reserves this PID so GDB can represent the idle thread's zero ID. */
#define PADOS_IDLE_THREAD_ID INT32_MAX

/* Bound reads and allocations when the target contains incomplete data. */
#define PADOS_MAX_THREADS (1024 * 1024)
#define PADOS_INITIAL_THREAD_CAPACITY 128
#define PADOS_MAX_NAME_SIZE 256
#define PADOS_MAX_STATES 32
#define PADOS_STATE_NAME_SIZE 32
#define PADOS_MAX_FRAME_SIZE 256

#endif /* OPENOCD_RTOS_PADOS_H */
